/**
 * Domain Events (Dictionary)
 * Centraliza todos los eventos de la aplicación para evitar errores tipográficos (Typo-safe).
 */
export const MES_EVENTS = {
  // Workflow & Navigation
  WORKFLOW_STARTED: 'WORKFLOW_STARTED',
  WORKFLOW_FINISHED: 'WORKFLOW_FINISHED',
  WORKFLOW_CANCELLED: 'WORKFLOW_CANCELLED',
  
  // Scanners
  QR_SCANNED: 'QR_SCANNED',
  SCANNER_ERROR: 'SCANNER_ERROR',
  
  // Capabilities
  RECEPTION_COMPLETED: 'RECEPTION_COMPLETED',
  RECEPTION_FAILED: 'RECEPTION_FAILED',
  RECEPTION_QR_RESOLVED: 'RECEPTION_QR_RESOLVED',

  // System
  NETWORK_OFFLINE: 'NETWORK_OFFLINE',
  NETWORK_ONLINE: 'NETWORK_ONLINE',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',

  // Observability & Telemetry
  WORKSPACE_OPENED: 'WORKSPACE_OPENED',
  WORKSPACE_CLOSED: 'WORKSPACE_CLOSED',
  WORKFLOW_COMPLETED: 'WORKFLOW_COMPLETED',
  WORKFLOW_CANCELLED: 'WORKFLOW_CANCELLED',
  SCANNER_TIMEOUT: 'SCANNER_TIMEOUT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SAVE_SUCCEEDED: 'SAVE_SUCCEEDED',
  SAVE_FAILED: 'SAVE_FAILED',
  SLA_OK: 'SLA_OK',
  SLA_FAILED: 'SLA_FAILED',

  // UI Observability
  BUTTON_CLICKED: 'BUTTON_CLICKED',
  ACTIONBAR_PRIMARY_TRIGGERED: 'ACTIONBAR_PRIMARY_TRIGGERED',
  SCANNER_OPENED: 'SCANNER_OPENED',
  SCANNER_CLOSED: 'SCANNER_CLOSED',
  STATUS_RENDERED: 'STATUS_RENDERED',

  // Quality & Telemetry
  CONTRACT_TEST_FAILED: 'CONTRACT_TEST_FAILED',
  VISUAL_REGRESSION: 'VISUAL_REGRESSION',
  ACCESSIBILITY_WARNING: 'ACCESSIBILITY_WARNING',
  INTERACTION_TIMEOUT: 'INTERACTION_TIMEOUT',
  PERFORMANCE_THRESHOLD_EXCEEDED: 'PERFORMANCE_THRESHOLD_EXCEEDED'
};
